// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course_v2/internal/cart/delivery/http"
	"go_online_course_v2/internal/cart/repository"
	"go_online_course_v2/internal/cart/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.CartHandler {
	cartRepository := repository.NewCartRepository(db)
	cartUseCase := usecase.NewCartUseCase(cartRepository)
	cartHandler := http.NewCartHandler(cartUseCase)
	return cartHandler
}
