// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course_v2/internal/discount/delivery"
	"go_online_course_v2/internal/discount/repository"
	"go_online_course_v2/internal/discount/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *delivery.DiscountHandler {
	discountRepository := repository.NewDiscountRepository(db)
	discountUseCase := usecase.NewDiscountUseCase(discountRepository)
	discountHandler := delivery.NewDiscountHandler(discountUseCase)
	return discountHandler
}
