// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course_v2/internal/product/delivery/http"
	"go_online_course_v2/internal/product/repository"
	"go_online_course_v2/internal/product/usecase"
	repository2 "go_online_course_v2/internal/product_category/repository"
	"go_online_course_v2/pkg/media/cloudinary"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.ProductHandler {
	productRepository := repository.NewProductRepository(db)
	productCategoryRepository := repository2.NewProductCategoryRepository(db)
	media := cloudinary.NewMediaUseCase()
	productUseCase := usecase.NewProductUseCase(productRepository, productCategoryRepository, media)
	productHandler := http.NewProductHandler(productUseCase)
	return productHandler
}
