// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course_v2/internal/register/delivery/http"
	usecase2 "go_online_course_v2/internal/register/usecase"
	"go_online_course_v2/internal/user/repository"
	"go_online_course_v2/internal/user/usecase"
	"go_online_course_v2/pkg/mail/mailersend"
	"go_online_course_v2/pkg/mail/sendgrid"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.RegisterHandler {
	userRepository := repository.NewUserRepository(db)
	userUseCase := usecase.NewUserUseCase(userRepository)
	mail := sendgrid.NewMailUseCase()
	mailersendMail := mailersend.NewMailUseCase()
	registerUseCase := usecase2.NewRegisterUseCase(userUseCase, mail, mailersendMail)
	registerHandler := http.NewRegisterHandler(registerUseCase)
	return registerHandler
}
