// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	repository3 "go_online_course_v2/internal/admin/repository"
	usecase2 "go_online_course_v2/internal/admin/usecase"
	repository2 "go_online_course_v2/internal/oauth/repository"
	usecase3 "go_online_course_v2/internal/oauth/usecase"
	"go_online_course_v2/internal/profile/delivery/http"
	usecase4 "go_online_course_v2/internal/profile/usecase"
	"go_online_course_v2/internal/user/repository"
	"go_online_course_v2/internal/user/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.ProfileHandler {
	userRepository := repository.NewUserRepository(db)
	userUseCase := usecase.NewUserUseCase(userRepository)
	oauthClientRepository := repository2.NewOauthClientRepository(db)
	oauthAccessTokenRepository := repository2.NewOauthAccessTokenRepository(db)
	oauthRefreshTokenRepository := repository2.NewOauthRefreshTokenRepository(db)
	adminRepository := repository3.NewAdminRepository(db)
	adminUseCase := usecase2.NewAdminUseCase(adminRepository)
	oauthUseCase := usecase3.NewOauthUseCase(oauthClientRepository, oauthAccessTokenRepository, oauthRefreshTokenRepository, userUseCase, adminUseCase)
	profileUseCase := usecase4.NewProfileUseCase(userUseCase, oauthUseCase)
	profileHandler := http.NewProfileHandler(profileUseCase)
	return profileHandler
}
