// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course_v2/internal/forgot_password/delivery/http"
	"go_online_course_v2/internal/forgot_password/repository"
	usecase2 "go_online_course_v2/internal/forgot_password/usecase"
	repository2 "go_online_course_v2/internal/user/repository"
	"go_online_course_v2/internal/user/usecase"
	"go_online_course_v2/pkg/mail/mailersend"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.ForgotPasswordHandler {
	forgotPasswordRepository := repository.NewForgotPasswordRepository(db)
	userRepository := repository2.NewUserRepository(db)
	userUseCase := usecase.NewUserUseCase(userRepository)
	mail := mailersend.NewMailUseCase()
	forgotPasswordUseCase := usecase2.NewForgotPasswordUseCase(forgotPasswordRepository, userUseCase, mail)
	forgotPasswordHandler := http.NewForgotPasswordHandler(forgotPasswordUseCase)
	return forgotPasswordHandler
}
