// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go_online_course_v2/internal/admin/delivery/http"
	"go_online_course_v2/internal/admin/repository"
	"go_online_course_v2/internal/admin/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *http.AdminHandler {
	adminRepository := repository.NewAdminRepository(db)
	adminUseCase := usecase.NewAdminUseCase(adminRepository)
	adminHandler := http.NewAdminHandler(adminUseCase)
	return adminHandler
}
